var strings = {
  title: '诗词画册',
  new: '添加',
  search: '搜索',
  shi: '诗',
  ci: '词',
  poem_category: '体裁',
  poem_cipai: '词牌',
  poem_cipai_tip: '有词牌可不填',
  poem_type: '类型',
  poem_title: '标题',
  poem_prologue: '序跋',
  poem_period: '时代',
  poem_author: '作者',
  poem_author_desc: '介绍',
  poem_content: '正文',
  poem_desc: '简介',
  poem_annotation: '注解',
  poem_image: '配图',
  poem_music: '配乐',
  input_tip: '请输入',
  input_required: '请填写所有必填内容',
  prev: '后退',
  next: '前进',
  submit: '提交',
  no_content: '暂无内容',
  favorite_success: '收藏成功',
  select_image_tip: '请选择图片文件',
}
module.exports = { strings }